#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fase Uno della campagna archivistica: costruisce repertorio/ARCHIVI_OPERATIVO.xlsx,
una riga per sede, dai dati dell'elenco «SEDI ACCERTATE» del prompt canonico.

Le sedi sono gia' verificate (non si riverificano): qui si trascrivono i loro estremi
e si registra il dominio ufficiale, il solo dato mancante. I domini gia' noti (dai 18
elencati in coda al prompt, o accertati per ricerca) sono precompilati; gli altri sono
marcati «DA CERCARE» finche' la ricerca non li chiude.

I file di servizio (xlsx) sono esenti dalla regola dei numeri per esteso: qui si usano
le cifre per leggibilita'. Data di controllo: 6.8.2026.
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment

DATA = "6.8.2026"
DA_CERCARE = "DA CERCARE"

COLONNE = [
    "Denominazione ufficiale (lingua originale)",
    "Denominazione italiana",
    "Stato",
    "Città e indirizzo",
    "Base normativa istitutiva",
    "Consistenza misurata",
    "Ambito cronologico",
    "Procedura d'accesso",
    "Limiti e vincoli dichiarati",
    "Consultazione remota",
    "Strumenti di corredo / fondi pertinenti",
    "Rilevanza per l'opera",
    "Dominio sito ufficiale",
    "Stato di verifica",
    "Data controllo",
]

# Ogni sede: i 12 campi descrittivi + dominio (o DA_CERCARE). Raggruppate per area.
SEDI = [
 # ---------------- ITALIA ----------------
 ("ITALIA", [
  ("Archivio centrale dello Stato", "Archivio centrale dello Stato", "Italia",
   "Roma, piazzale degli Archivi 27, EUR",
   "Autonomia speciale; erede dell'Archivio del Regno (1875), autonomo dal 1953, aperto al pubblico nel 1960",
   "160 km lineari",
   "dal 1861 (unità); erede dell'Archivio del Regno 1875",
   "Consultazione libera ex art. 122 Codice dei beni culturali",
   "Documenti riservati e relativi a situazioni private secondo i termini del Codice",
   "Teca digitale dal 2022",
   "Fondo «Archivi fascisti»: segreteria particolare del capo del governo, PNF, Milizia, Brigate Nere, GNR, PFR; archivio del CLN centrale (fondo non censito dal repertorio)",
   "Massima: carte del fascismo e della RSI",
   "acs.beniculturali.it"),
  ("Archivio storico del Senato della Repubblica", "Archivio storico del Senato della Repubblica", "Italia",
   "Roma, via della Dogana Vecchia 29",
   "Istituito nel 2001, aperto nel 2003",
   "n.d. (acquisisce archivi privati dei parlamentari)",
   "dalla prima legislatura repubblicana; fondo Commissione stragi",
   "Consultabili i fascicoli personali dei senatori dalla I alla VI legislatura",
   "Vincoli sui fascicoli personali e sui materiali riservati della Commissione",
   "n.d.",
   "Fondo Commissione stragi per subfondi: Alto Adige, Argo 16, Bologna, Calabresi, Cirillo, eversione di destra, Gladio. Citazione: ASSR, Terrorismo e stragi (X-XIII leg.), 2.3",
   "Massima: Commissione stragi",
   DA_CERCARE),
  ("Archivio storico della Camera dei deputati", "Archivio storico della Camera dei deputati", "Italia",
   "Roma, piazza San Macuto 57 (Palazzo del Seminario)",
   "Aperto al pubblico dal 1991",
   "n.d.",
   "documenti delle Commissioni d'inchiesta conclusesi alla Camera; fondi personali",
   "Massimo 5 buste per richiesta, 4 richieste al giorno",
   "Testo trascrivibile e pubblicabile solo parzialmente; pubblicazione integrale su autorizzazione del Sovrintendente; segreto funzionale derogabile dal Presidente della Camera",
   "n.d.",
   "Fondi personali Cossiga, Pacciardi, Seniga; atti Commissioni d'inchiesta",
   "Alta: Commissioni d'inchiesta e fondi personali",
   DA_CERCARE),
  ("Archivio storico diplomatico del Ministero degli Affari esteri",
   "Archivio storico diplomatico del Ministero degli Affari esteri", "Italia",
   "Roma, Farnesina",
   "Istituito nel 1902",
   "circa 30 km lineari",
   "documenti anteriori al cinquantennio; 30-50 anni con procedura speciale; situazioni private dopo 70 anni",
   "Consultabili gli anteriori al cinquantennio; 30-50 anni con procedura speciale ex DM 22.12.2015; privati solo dopo 70 anni",
   "Il ministero non versa all'ACS; 2 buste/giorno (3 una tantum per chi viene da fuori Roma), da richiedere entro le 11 del giorno prima; sala studio chiusa 23.2-31.10.2026, servizio ridotto",
   "n.d.",
   "Archivi Esteri RSI 1943-45; ministero Africa italiana; fondo Minculpop; Gabinetto Archivio riservato. Guida alle fonti diplomatiche italiane sulla cooperazione europea 1947-57 con banca dati",
   "Alta: diplomazia e apparati RSI/coloniali",
   DA_CERCARE),
  ("Centro di documentazione Cultura della Legalità Democratica",
   "Centro di documentazione Cultura della Legalità Democratica (Regione Toscana)", "Italia",
   "Firenze",
   "Regione Toscana",
   "copia di 541 fascicoli per 8.845 documenti della Commissione stragi",
   "materiali Commissione stragi",
   "Via d'accesso alternativa a un fondo altrimenti consultabile solo a Roma",
   "n.d.",
   "n.d.",
   "Copia dei fascicoli della Commissione stragi (non censito dal repertorio)",
   "Media: via d'accesso alternativa alla Commissione stragi",
   DA_CERCARE),
  ("Centro documentazione Archivio Flamigni", "Centro documentazione Archivio Flamigni", "Italia",
   "Oriolo Romano (Viterbo)",
   "Istituto culturale nato nel 2005",
   "n.d.",
   "n.d.",
   "Da accertare: il titolare del fondo è morto nel dicembre 2025 (conseguenze su titolarità e accesso)",
   "Titolarità e accesso da riaccertare dopo il decesso del titolare (12.2025)",
   "n.d.",
   "Fondo Flamigni su terrorismo, Moro, Gladio",
   "Alta: fondo Flamigni; accesso da riaccertare",
   DA_CERCARE),
  ("Rete degli archivi per non dimenticare", "Rete degli archivi per non dimenticare", "Italia",
   "Portale nazionale",
   "Inaugurato il 9.5.2011 dal Presidente della Repubblica",
   "n.d. (aggregatore)",
   "stragi e terrorismo in Italia repubblicana",
   "Accesso gratuito, registrazione facoltativa",
   "n.d.",
   "Ricerca filtrabile per eventi, persone, indagini e processi, documenti, organizzazioni e uffici; sezione «Muro della Memoria»",
   "Ricerca per eventi/persone/indagini/documenti/organizzazioni; registro nominale delle vittime",
   "Alta: banca dati nodale sul dominio dell'opera",
   DA_CERCARE),
  ("Centro siciliano di documentazione Giuseppe Impastato",
   "Centro siciliano di documentazione Giuseppe Impastato", "Italia",
   "Palermo, via Villa Sperlinga 15",
   "Fondato nel 1977",
   "n.d.",
   "mafia e delitti politici",
   "n.d.",
   "n.d.",
   "n.d.",
   "Documentazione su mafia e terrorismo",
   "Media: documentazione antimafia",
   DA_CERCARE),
  ("Archivi storici dell'Unione europea", "Archivi storici dell'Unione europea", "Italia",
   "Firenze, Villa Salviati, via Bolognese",
   "Operativi dal 2012",
   "circa 150 fondi privati di persone/movimenti/organizzazioni oltre ai fondi istituzionali",
   "consultabile fino al 1996 circa (regola dei 30 anni)",
   "Regola dei 30 anni: consultabile fino al 1996 circa",
   "I fondi riservati restano a Lussemburgo (edificio Konrad Adenauer)",
   "n.d.",
   "Fondi privati dell'integrazione europea; documenti istituzionali UE",
   "Media: integrazione europea",
   DA_CERCARE),
 ]),
 # ------- EUROPA CENTRO-ORIENTALE (rete Berlino 16.12.2008) -------
 ("EUROPA CENTRO-ORIENTALE", [
  ("Instytut Pamięci Narodowej", "Istituto polacco della memoria nazionale", "Polonia",
   "Varsavia, via Postępu 18 (+ 11 sedi distaccate)",
   "Legge del 18.12.1998, operativo dal 1.7.2000",
   "n.d.",
   "atti degli organi di sicurezza 22.7.1944 - 31.12.1989, compresi intelligence e controintelligence civile e militare",
   "Accesso agli stranieri su base di reciprocità (da accertare per un ricercatore italiano)",
   "Reciprocità per gli stranieri",
   "Inventario in rete",
   "Atti degli organi di sicurezza 1944-1989",
   "Alta: sicurezza polacca, controspionaggio",
   "inwentarz.ipn.gov.pl"),
  ("Consiliul Naţional pentru Studierea Arhivelor Securităţii (CNSAS)",
   "Consiglio romeno per lo studio degli archivi della Securitate", "Romania",
   "Bucarest",
   "Fondato nel 2000, legge del dicembre 1999",
   "25 km lineari, oltre 2 milioni di volumi (circa 5.000 documenti/metro; circa 200 pagine/fascicolo)",
   "documenti della Securitate",
   "Consultazione degli archivi della Securitate",
   "Pubblica solo la parte che non riguarda la sicurezza nazionale (termine mai definito); ordinato secondo la logica della Securitate",
   "n.d.",
   "Archivi della Securitate ordinati secondo la logica del servizio",
   "Alta: Securitate",
   DA_CERCARE),
  ("Archiv bezpečnostních složek", "Archivio ceco dei servizi di sicurezza", "Repubblica Ceca",
   "Praga (Branické náměstí, Na Struze); Kanice presso Brno",
   "n.d.",
   "748 fondi per quasi 20.000 metri lineari (1.1.2017)",
   "documenti dei servizi di sicurezza cecoslovacchi",
   "Consultazione remota dal 2016 per ricercatori registrati",
   "I fascicoli d'indagine dell'ex Sicurezza pubblica vanno richiesti al terzo dipartimento (fuori dai sistemi di registrazione)",
   "Sì: remota dal 2016 per ricercatori registrati",
   "748 fondi dei servizi di sicurezza",
   "Alta: StB cecoslovacca; accesso remoto",
   DA_CERCARE),
  ("Állambiztonsági Szolgálatok Történeti Levéltára (ÁBTL)",
   "Archivio storico della sicurezza di Stato ungherese", "Ungheria",
   "Budapest, Eötvös utca 7",
   "Legge del 2003 (ufficio storico dal 1997)",
   "n.d.",
   "documenti della sicurezza di Stato ungherese",
   "Due vie di ricerca: accademica e privata",
   "n.d.",
   "n.d.",
   "Trascrizioni di conversazioni intercettate, verbali di interrogatorio, materiali sequestrati",
   "Alta: sicurezza di Stato ungherese",
   "abtl.hu"),
  ("Комисия за разкриване на документите (COMDOS)",
   "Comitato bulgaro per la divulgazione dei documenti", "Bulgaria",
   "Sofia",
   "n.d.",
   "n.d.",
   "documenti della Sicurezza di Stato e dei servizi informativi dell'Esercito popolare",
   "Consultazione dei documenti divulgati",
   "n.d.",
   "n.d.",
   "Sicurezza di Stato e intelligence militare bulgara",
   "Media-alta: sicurezza bulgara",
   DA_CERCARE),
  ("Ústav pamäti národa (ÚPN)", "Istituto slovacco della memoria della nazione", "Slovacchia",
   "Bratislava",
   "Legge del 2002 (approvata superando il veto del capo dello Stato)",
   "n.d.",
   "documenti della sicurezza di Stato cecoslovacca (parte slovacca)",
   "n.d.",
   "n.d.",
   "n.d.",
   "Documenti della StB slovacca",
   "Media: sicurezza slovacca",
   DA_CERCARE),
  ("Autoriteti për Informimin mbi Dokumentet e ish-Sigurimit të Shtetit",
   "Autorità albanese sui documenti dell'ex Sicurezza di Stato", "Albania",
   "Tirana",
   "n.d.",
   "n.d.",
   "documenti del Sigurimi dal 1944 al 1991",
   "Accessibili dal 2017",
   "n.d.",
   "n.d.",
   "Documenti del Sigurimi 1944-1991",
   "Media: Sigurimi albanese",
   DA_CERCARE),
  ("Lietuvos ypatingasis archyvas", "Archivio speciale lituano", "Lituania",
   "Vilnius, Gedimino 40/1 (ex quartier generale del KGB)",
   "n.d.",
   "oltre 1.350.000 fascicoli, più di 17.000 metri lineari, tre fondi",
   "documenti del KGB in Lituania",
   "n.d.",
   "Le copie microfilmate inviate a un istituto estero recano espunzioni; i fascicoli rimossi sono indicati nell'elenco del contenuto di ciascuna bobina",
   "n.d.",
   "Fascicoli del KGB; tre fondi",
   "Alta: KGB in Lituania",
   DA_CERCARE),
  ("Latvijas Nacionālais arhīvs", "Archivi nazionali lettoni", "Lettonia",
   "Riga",
   "n.d.",
   "n.d.",
   "documenti del servizio sovietico e del Comitato centrale",
   "Registrazione obbligatoria",
   "n.d.",
   "Pubblicati in rete: schedari alfabetici, fascicoli degli agenti reclutati, elenchi telefonici dei funzionari",
   "Schedari alfabetici, fascicoli degli agenti, elenchi telefonici; materiali del CC",
   "Alta: KGB/agenti in Lettonia",
   "kgb.arhivi.lv"),
 ]),
 # ---------------- PENISOLA IBERICA ----------------
 ("PENISOLA IBERICA", [
  ("Arquivo Nacional Torre do Tombo", "Archivio Nazionale Torre do Tombo", "Portogallo",
   "Lisbona, Alameda da Universidade",
   "Istituito nel 1378",
   "140 km lineari; oltre 2.140 fondi (il repertorio ne censiva uno)",
   "dal medioevo all'età contemporanea",
   "Accesso libero sopra i 16 anni; il fondo della polizia politica è soggetto a regolamento proprio",
   "Fondo polizia politica (PIDE/DGS) con regolamento proprio",
   "n.d.",
   "Servizi di centralizzazione informazioni Mozambico e Angola; archivio personale del capo del governo; servizi di coordinamento dell'estinzione della polizia politica; cooperativa dei funzionari; Legione Portoghese; ministero dell'Interno (fondi non censiti)",
   "Massima: PIDE/DGS, colonie, Legione Portoghese",
   DA_CERCARE),
  ("Centro Documental de la Memoria Histórica", "Centro Documentale della Memoria Storica", "Spagna",
   "Salamanca",
   "Regio decreto del 1.6.2007",
   "n.d.",
   "1936-1978",
   "Consultazione (molte scatole non catalogate né descritte)",
   "Documentazione non digitalizzata; molte scatole non catalogate né descritte",
   "n.d.",
   "Fondo del Tribunale speciale per la repressione della massoneria e del comunismo: censimenti, credenziali, certificati, corrispondenza delle logge",
   "Alta: repressione massoneria e comunismo",
   DA_CERCARE),
 ]),
 # ---------------- FRANCIA E GERMANIA ----------------
 ("FRANCIA E GERMANIA", [
  ("Archives nationales", "Archivi nazionali francesi", "Francia",
   "Pierrefitte-sur-Seine",
   "n.d.",
   "383 km lineari",
   "dalla Rivoluzione in poi (Stato francese) e archivi privati",
   "Accesso secondo la disciplina francese sugli archivi pubblici",
   "n.d.",
   "n.d.",
   "Archivi dello Stato francese post-1789 e archivi privati",
   "Media-alta: Stato francese",
   DA_CERCARE),
  ("Service historique de la Défense", "Servizio storico della Difesa", "Francia",
   "Vincennes (+ 9 sedi)",
   "n.d.",
   "oltre 450 km su 9 sedi",
   "amministrazione militare d'oltremare dal 1940; fondi ministeriali",
   "Legge del 2008: comunicabilità di pieno diritto, ma istruzione interministeriale del 19.5.1952 impone declassificazione preventiva (termine di 2 mesi raramente rispettato)",
   "Gli archivi della gendarmeria non risalgono oltre la seconda metà dell'Ottocento («en raison d'importantes destructions»)",
   "n.d.",
   "SGDSN; Gabinetto del ministro; Stato maggiore interforze; amministrazione militare d'oltremare; Gendarmerie nationale e gendarmerie specializzate",
   "Alta: difesa, oltremare, gendarmeria",
   DA_CERCARE),
  ("Bundesarchiv", "Archivio federale tedesco", "Germania",
   "Coblenza; Potsdamer Straße 1 (+ 23 sedi in 14 dipartimenti)",
   "n.d.",
   "n.d.",
   "atti federali tedeschi",
   "Ogni persona ha diritto di utilizzare gli atti su domanda",
   "n.d.",
   "n.d.",
   "Atti federali tedeschi",
   "Alta: Stato federale tedesco",
   DA_CERCARE),
  ("Stasi-Unterlagen-Archiv (im Bundesarchiv)",
   "Archivio degli atti della sicurezza di Stato della RDT (nel Bundesarchiv)", "Germania",
   "Berlino e sedi regionali",
   "Confluito nel Bundesarchiv dal 17.6.2021 senza spostamento fisico; legge speciale",
   "circa 111 km di atti",
   "atti della Stasi (MfS)",
   "Si applica la legge speciale (non la disciplina generale): modulo di domanda distinto",
   "Disciplina speciale distinta da quella del Bundesarchiv",
   "n.d.",
   "Atti del MfS; apertura resa possibile dall'occupazione delle sedi 1989-90 (fine della distruzione in corso)",
   "Massima: Stasi",
   DA_CERCARE),
 ]),
 # ---------------- GRECIA E TURCHIA ----------------
 ("GRECIA E TURCHIA", [
  ("Γενικά Αρχεία του Κράτους (GAK)", "Archivi generali dello Stato greco", "Grecia",
   "Atene, via Dafnis 61 (+ 37 sedi)",
   "Creati nel 1914",
   "n.d.",
   "fondi ministeriali, fra cui il militare",
   "Le postazioni interne consentono la consultazione di materiale non accessibile dall'esterno",
   "Parte del materiale accessibile solo dalle postazioni interne",
   "n.d.",
   "Fondi ministeriali, incluso il militare",
   "Media-alta: apparati statali greci",
   "arxeiomnimon.gak.gr"),
  ("Devlet Arşivleri Başkanlığı", "Direzione degli archivi di Stato della Turchia", "Turchia",
   "Ankara e Istanbul",
   "Decreto presidenziale del 16.7.2018 (già direzione generale dal 1984); dipende dalla Presidenza della Repubblica",
   "n.d.",
   "documenti di Stato ottomani e repubblicani",
   "Ricercatori turchi e stranieri accedono gratuitamente per scopi non commerciali, con iscrizione in sede o via portale nazionale",
   "Uso non commerciale",
   "Sì: catalogo remoto",
   "Catalogo remoto; ammissione esplicita degli stranieri",
   "Media: apparati turchi",
   "katalog.devletarsivleri.gov.tr"),
 ]),
 # ---------------- REGNO UNITO ----------------
 ("REGNO UNITO", [
  ("The National Archives", "Archivi Nazionali del Regno Unito", "Regno Unito",
   "Kew, Londra",
   "n.d.",
   "serie FCO 141: circa 8.800 fascicoli da 37 territori (Operation Legacy); quasi 20.000 fascicoli trasferiti dal 2012",
   "«archivi migrati» coloniali",
   "Ammessi il 7.4.2011 (FCO 141)",
   "88.000 documenti di Hong Kong restano a Hanslope Park, in parte vincolati fino al 2047; non resi pubblici l'inventario né gli elenchi dei fascicoli distrutti",
   "Catalogo in rete",
   "FCO 141 «migrated archives»; Operation Legacy",
   "Alta: archivi coloniali migrati",
   DA_CERCARE),
  ("Churchill Archives Centre", "Churchill Archives Centre", "Regno Unito",
   "Cambridge",
   "n.d.",
   "n.d.",
   "carte di personalità del Novecento",
   "Consultazione su prenotazione",
   "n.d.",
   "n.d.",
   "Carte dell'ufficiale sovietico transfugo",
   "Media: transfughi sovietici",
   DA_CERCARE),
 ]),
 # ---------------- SANTA SEDE ----------------
 ("SANTA SEDE", [
  ("Archivum Apostolicum Vaticanum", "Archivio Apostolico Vaticano", "Santa Sede",
   "Città del Vaticano",
   "n.d.",
   "85 km di scaffalature, oltre 600 fondi su circa 12 secoli",
   "consultabile fino al 9.10.1958 e non oltre",
   "Requisiti: laurea magistrale, lettera di presentazione, certificato del titolo",
   "Non consultabile oltre il 9.10.1958 (da dichiarare accanto a ogni rinvio); chiusura annuale il 15 luglio",
   "n.d.",
   "Oltre 600 fondi su 12 secoli",
   "Media: limite 1958 sul periodo dell'opera",
   DA_CERCARE),
  ("Archivio storico della Sezione per i Rapporti con gli Stati",
   "Archivio storico della Sezione per i Rapporti con gli Stati", "Santa Sede",
   "Città del Vaticano",
   "n.d.",
   "corrispondenza diplomatica",
   "pontificato aperto",
   "Integralmente digitalizzato per il pontificato aperto",
   "n.d.",
   "Sì: consultazione simultanea dello stesso documento da parte di più ricercatori",
   "Corrispondenza diplomatica della Santa Sede",
   "Alta: diplomazia vaticana",
   DA_CERCARE),
  ("Archivio del Dicastero per la Dottrina della Fede",
   "Archivio del Dicastero per la Dottrina della Fede", "Santa Sede",
   "Città del Vaticano",
   "n.d.",
   "n.d.",
   "posizione dottrinale sulla massoneria",
   "Domanda con commendatizia di autorità ecclesiastica o accademica; consultazione previa prenotazione, in ordine di arrivo",
   "Commendatizia richiesta; permesso scade il 15 luglio di ogni anno",
   "n.d.",
   "Sede propria della posizione dottrinale sulla massoneria",
   "Alta: dottrina sulla massoneria",
   DA_CERCARE),
 ]),
 # ---------------- ORGANISMI INTERNAZIONALI ----------------
 ("ORGANISMI INTERNAZIONALI", [
  ("NATO Archives", "Archivio dell'Organizzazione del Trattato dell'Atlantico del Nord", "Internazionale",
   "Bruxelles",
   "Inaugurato il 19.5.1999 con circa 33.000 documenti declassificati",
   "oltre 40.000 documenti in rete; collezione completa per il 1949-1959, serie ulteriori fino agli anni Novanta",
   "1949 - anni Novanta",
   "Trent'anni e declassificazione secondo C-M(55)15(Final)",
   "Riservatezza personale: vincolo di 100 anni dalla data di nascita; deroga per decisione del Consiglio; l'assenza di un documento = «non ancora esaminato»",
   "Sì: oltre 40.000 documenti in rete",
   "Collezione completa 1949-59; serie fino agli anni Novanta",
   "Alta: Alleanza atlantica",
   "archives.nato.int"),
  ("Historical Archives of the European Parliament", "Archivi storici del Parlamento europeo", "Internazionale",
   "n.d.",
   "n.d.",
   "oltre 5 milioni di registrazioni, risalenti al 1952",
   "dal 1952",
   "Consultazione degli archivi parlamentari",
   "n.d.",
   "n.d.",
   "Oltre 5 milioni di registrazioni, comprese le interrogazioni parlamentari",
   "Media: Parlamento europeo",
   DA_CERCARE),
  ("Service des archives historiques de la Commission européenne",
   "Servizio degli archivi storici della Commissione europea", "Internazionale",
   "Bruxelles",
   "n.d.",
   "n.d.",
   "documenti della Commissione europea",
   "Consultazione (deposito a Firenze selezionato da questo servizio)",
   "n.d.",
   "n.d.",
   "È il soggetto che seleziona ciò che sarà depositato a Firenze (chi voglia sapere cosa non è stato trasferito si rivolge qui)",
   "Media: selezione del deposito UE",
   DA_CERCARE),
 ]),
 # ---------------- STATI UNITI ----------------
 ("STATI UNITI", [
  ("CIA Records Search Tool (CREST), National Archives",
   "Sistema di ricerca dell'agenzia informativa presso gli Archivi nazionali", "Stati Uniti",
   "College Park (Maryland)",
   "n.d.",
   "oltre 11 milioni di pagine",
   "documenti CIA declassificati",
   "La messa in rete è il risultato di una causa (prima: solo lun-ven in orario d'ufficio)",
   "Alcuni documenti non appartengono ad alcuna raccolta e sfuggono a ricerche limitate per raccolta",
   "Sì: in rete dopo la causa",
   "Oltre 11 milioni di pagine CIA",
   "Massima: CIA",
   DA_CERCARE),
  ("U.S. Department of State Reading Room / FOIA",
   "Sala di lettura del Dipartimento di Stato", "Stati Uniti",
   "Stati Uniti (online)",
   "Legge del 1974 sulla conservazione dei materiali presidenziali (per le trascrizioni)",
   "Cile oltre 23.000 documenti (1968-1991); Argentina ~20 anni di lavoro (1975-83); El Salvador e Guatemala; trascrizioni telefoniche del Segretario di Stato 9.1973-12.1976",
   "1968-1991 (Cile) e progetti collegati",
   "Consultazione online dei progetti di desecretazione",
   "n.d.",
   "Sì: progetti di desecretazione online",
   "Progetti di desecretazione Cile/Argentina/El Salvador/Guatemala; trascrizioni telefoniche del Segretario di Stato",
   "Alta: desecretazioni Cono Sud",
   DA_CERCARE),
  ("National Security Archive", "National Security Archive", "Stati Uniti",
   "Washington, George Washington University, Gelman Library",
   "Fondato nel 1985, senza finanziamenti governativi",
   "oltre 15 milioni di pagine desecretate, più di 70.000 istanze, oltre 50 cause",
   "documenti desecretati del secondo Novecento",
   "Consultazione (istituto privato)",
   "Reperto metodologico: due versioni del medesimo scambio (1987) esaminate a 10 giorni di distanza recano espunzioni diverse",
   "Sì: briefing books e collezioni online",
   "Oltre 15 milioni di pagine desecretate via FOIA",
   "Massima: FOIA, desecretazioni",
   "nsarchive.gwu.edu"),
 ]),
 # ---------------- AMERICA LATINA ----------------
 ("AMERICA LATINA", [
  ("Archivo del Terror (Centro de Documentación y Archivo)", "Archivos del Terror", "Paraguay",
   "Asunción, Museo de la Justicia, Palazzo di giustizia",
   "n.d.",
   "circa 700.000 pagine rinvenute il 22.12.1992",
   "Operazione Condor e repressione stroessnerista",
   "Registro Memoria del Mondo dal 2009",
   "n.d.",
   "n.d.",
   "Archivi della polizia di Stroessner; nodo Condor",
   "Massima: Operazione Condor",
   DA_CERCARE),
  ("Museo de las Memorias (Dictadura y Derechos Humanos)", "Museo de las Memorias", "Paraguay",
   "Asunción, calle Chile 1072 (fra Manduvirá e Jejuí)",
   "Ex sede della Dirección Nacional de Asuntos Técnicos",
   "n.d.",
   "centro di detenzione e tortura per oltre 30 anni",
   "Lun-ven 8-16, ingresso gratuito",
   "n.d.",
   "n.d.",
   "Ex «La Técnica»; addestramento alla controinsurrezione (colonnello USA dal 5.1956)",
   "Alta: repressione paraguaiana, formazione USA",
   DA_CERCARE),
  ("Archivo Nacional de la Memoria", "Archivo Nacional de la Memoria", "Argentina",
   "Buenos Aires",
   "Decreto del 16.12.2003; unità di un centro internazionale con decreto del 21.5.2025",
   "n.d.",
   "ultima dittatura argentina",
   "Fondo aperto, classificazione parziale e preliminare, accesso parziale, inventari in elaborazione",
   "Accesso parziale; inventari ancora in elaborazione",
   "n.d.",
   "Sede in ex centro clandestino (dal 11.2007)",
   "Alta: dittatura argentina",
   DA_CERCARE),
  ("Memoria Abierta", "Memoria Abierta", "Argentina",
   "Buenos Aires, Avenida Libertador 8151",
   "Alleanza di 8 organizzazioni, costituita nel 1999",
   "n.d.",
   "terrorismo di Stato in Argentina",
   "Consultazione (organizzazione della società civile)",
   "n.d.",
   "n.d.",
   "Tesauro sui diritti umani; indice dei sopravvissuti ai centri clandestini con luoghi di detenzione per persona",
   "Alta: mappa dei centri clandestini",
   DA_CERCARE),
  ("Museo de la Memoria y los Derechos Humanos", "Museo de la Memoria y los Derechos Humanos", "Cile",
   "Santiago del Cile, Avenida Matucana 501",
   "Inaugurato l'11.1.2010",
   "n.d.",
   "settembre 1973 - marzo 1990",
   "Consultazione; archivio digitale online",
   "n.d.",
   "Sì: archivio digitale su archivommdh.cl",
   "Decreti, bandi militari, elenchi nominativi, fascicoli di polizia",
   "Alta: dittatura cilena",
   "archivommdh.cl"),
  ("Archivo Nacional de la Memoria (Archivo Nacional de Chile)",
   "Archivio Nazionale della Memoria cileno", "Cile",
   "Santiago del Cile, presso l'Archivio nazionale",
   "n.d.",
   "n.d.",
   "documenti sulla repressione cilena",
   "Incorporati solo i fondi con qualche livello di descrizione",
   "Solo una proporzione minore è digitalizzata",
   "Parziale",
   "Fondi con descrizione minima; digitalizzazione parziale",
   "Media-alta: repressione cilena",
   "archivonacional.cl"),
  ("Archivo General de la Nación", "Archivio Generale della Nazione uruguaiano", "Uruguay",
   "Montevideo",
   "Legge del maggio 2024 (documentazione trasferita dal ministero della Difesa nel 2019)",
   "1.218 rulli di microfilm, oltre 3 milioni di immagini",
   "sorveglianza politica del secondo Novecento",
   "Consultazione del fondo recuperato",
   "n.d.",
   "n.d.",
   "Schede personali, rapporti di intelligence, elenchi di sospetti, registri di sorveglianza. Nel 2023 un anonimo caricò in rete oltre 1.500 rulli digitalizzati",
   "Alta: intelligence uruguaiana",
   DA_CERCARE),
  ("Comisión de la Verdad (Bolivia)", "Commissione boliviana per la verità", "Bolivia",
   "La Paz",
   "Legge del 21.8.2017 (art. 7: desecretazione dei documenti militari e di polizia)",
   "Relazione finale marzo 2021, 11 tomi",
   "1964-1982 circa",
   "Accedette alla documentazione classificata delle Forze Armate",
   "Le Forze Armate dovranno ancora desecretare l'enorme documentazione rimasta",
   "n.d.",
   "Unica Commissione del continente ad accedere ai documenti classificati delle FF.AA.",
   "Alta: repressione boliviana",
   DA_CERCARE),
  ("Archivo Histórico de la Policía Nacional", "Archivio storico della Polizia Nazionale", "Guatemala",
   "Guatemala, avenida La Pedrera",
   "Rinvenuto nel luglio 2005",
   "n.d.",
   "documenti della polizia nazionale guatemalteca",
   "Sala di lettura pubblica dal 2009",
   "n.d.",
   "n.d.",
   "Archivio della Policía Nacional guatemalteca",
   "Alta: repressione guatemalteca",
   DA_CERCARE),
  ("Memórias Reveladas (Arquivo Nacional)", "Memórias Reveladas", "Brasile",
   "Brasile, presso l'Archivio nazionale",
   "Istituito nel maggio 2009",
   "n.d.",
   "dittatura militare brasiliana",
   "Consultazione (esclusi i documenti rivelatori dell'intimità della vita privata)",
   "Esclusi i documenti sull'intimità della vita privata",
   "Sì: portale online",
   "Rete di riferimento sui documenti della dittatura brasiliana",
   "Alta: dittatura brasiliana",
   DA_CERCARE),
 ]),
 # ---------------- AFRICA AUSTRALE ----------------
 ("AFRICA AUSTRALE", [
  ("South African History Archive (SAHA)", "South African History Archive", "Sudafrica",
   "Johannesburg, Università del Witwatersrand (dal 2022)",
   "Fondato nel 1988",
   "oltre 800 metri lineari",
   "apartheid e transizione",
   "Consultazione; progetto Traces of Truth con Historical Papers dal 2003",
   "n.d.",
   "n.d.",
   "Progetto Traces of Truth; documenti sull'apartheid",
   "Alta: apartheid",
   DA_CERCARE),
 ]),
]

# Domini ufficiali risolti per ricerca (chiave = denominazione italiana, univoca).
# Sovrascrivono il segnaposto DA_CERCARE. Due sedi restano senza dominio ufficiale
# accertabile e si dichiarano «n.d.» (non si inventa cio' che non si e' trovato).
DOMINI_TROVATI = {
    "Archivio centrale dello Stato": "acs.cultura.gov.it",
    "Archivio storico del Senato della Repubblica": "archivionline.senato.it",
    "Archivio storico della Camera dei deputati": "archivio.camera.it",
    "Archivio storico diplomatico del Ministero degli Affari esteri": "esteri.it",
    "Centro di documentazione Cultura della Legalità Democratica (Regione Toscana)": "regione.toscana.it",
    "Centro documentazione Archivio Flamigni": "archivioflamigni.org",
    "Rete degli archivi per non dimenticare": "memoria.san.beniculturali.it",
    "Centro siciliano di documentazione Giuseppe Impastato": "centroimpastato.com",
    "Archivi storici dell'Unione europea": "archives.eui.eu",
    "Consiglio romeno per lo studio degli archivi della Securitate": "cnsas.ro",
    "Archivio ceco dei servizi di sicurezza": "abscr.cz",
    "Comitato bulgaro per la divulgazione dei documenti": "comdos.bg",
    "Istituto slovacco della memoria della nazione": "upn.gov.sk",
    "Autorità albanese sui documenti dell'ex Sicurezza di Stato": "aidssh.al",
    "Archivio speciale lituano": "lya.archyvai.lrv.lt",
    "Archivio Nazionale Torre do Tombo": "antt.dglab.gov.pt",
    "Centro Documentale della Memoria Storica": "cultura.gob.es",
    "Archivi nazionali francesi": "archives-nationales.culture.gouv.fr",
    "Servizio storico della Difesa": "servicehistorique.sga.defense.gouv.fr",
    "Archivio federale tedesco": "bundesarchiv.de",
    "Archivio degli atti della sicurezza di Stato della RDT (nel Bundesarchiv)": "bundesarchiv.de/stasi-unterlagen-archiv",
    "Archivi Nazionali del Regno Unito": "nationalarchives.gov.uk",
    "Churchill Archives Centre": "archives.chu.cam.ac.uk",
    "Archivio Apostolico Vaticano": "archivioapostolicovaticano.va",
    "Archivio storico della Sezione per i Rapporti con gli Stati": "vatican.va (romancuria/segreteria-di-stato/sds-archivio-storico)",
    "Archivio del Dicastero per la Dottrina della Fede": "acdf.va",
    "Archivi storici del Parlamento europeo": "europarl.europa.eu/historicalarchives",
    "Servizio degli archivi storici della Commissione europea": "commission.europa.eu (historical-archives-service)",
    "Sistema di ricerca dell'agenzia informativa presso gli Archivi nazionali": "cia.gov/readingroom",
    "Sala di lettura del Dipartimento di Stato": "foia.state.gov",
    "Archivos del Terror": "pj.gov.py (Museo de la Justicia)",
    "Museo de las Memorias": "n.d. — nessun dominio ufficiale accertato (Fondazione Celestina Pérez de Almada; presenza social)",
    "Archivo Nacional de la Memoria": "argentina.gob.ar/derechoshumanos/ANM",
    "Memoria Abierta": "memoriaabierta.org.ar",
    "Archivio Generale della Nazione uruguaiano": "agn.gub.uy",
    "Commissione boliviana per la verità": "n.d. — Commissione sciolta dopo l'informe 2021, nessun sito permanente (docum. presso justicia.gob.bo)",
    "Archivio storico della Polizia Nazionale": "archivohistoricopn.org",
    "Memórias Reveladas": "memoriasreveladas.gov.br",
    "South African History Archive": "saha.org.za",
}

def main():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Archivi operativi"

    hdr_fill = PatternFill("solid", fgColor="1F3864")
    hdr_font = Font(bold=True, color="FFFFFF", size=10)
    area_fill = PatternFill("solid", fgColor="D9E1F2")
    area_font = Font(bold=True, size=10, color="1F3864")
    cerca_fill = PatternFill("solid", fgColor="FFF2CC")  # giallo: dominio da cercare
    wrap = Alignment(wrap_text=True, vertical="top")

    # intestazione
    for j, c in enumerate(COLONNE, start=1):
        cell = ws.cell(1, j, c)
        cell.fill = hdr_fill
        cell.font = hdr_font
        cell.alignment = wrap
    ws.freeze_panes = "A2"

    r = 2
    n_sedi = 0
    n_noti = 0
    for area, sedi in SEDI:
        # riga-banda dell'area
        ws.cell(r, 1, area).font = area_font
        for j in range(1, len(COLONNE) + 1):
            ws.cell(r, j).fill = area_fill
        r += 1
        for sede in sedi:
            denom_orig, denom_ita, stato, citta, base, cons, ambito, accesso, limiti, remota, strumenti, rilev, dominio = sede
            # il dominio risolto per ricerca sovrascrive il segnaposto/prefill
            if denom_ita in DOMINI_TROVATI:
                dominio = DOMINI_TROVATI[denom_ita]
            non_accertato = (dominio == DA_CERCARE) or dominio.startswith("n.d.")
            esito = ("già verificata (SEDI ACCERTATE); dominio ufficiale "
                     + ("non accertato" if non_accertato else "accertato per ricerca il " + DATA))
            valori = [denom_orig, denom_ita, stato, citta, base, cons, ambito, accesso,
                      limiti, remota, strumenti, rilev, dominio, esito, DATA]
            for j, v in enumerate(valori, start=1):
                cell = ws.cell(r, j, v)
                cell.alignment = wrap
            if non_accertato:
                ws.cell(r, 13).fill = cerca_fill
            else:
                n_noti += 1
            r += 1
            n_sedi += 1

    # larghezze colonna
    larghezze = [30, 30, 14, 26, 30, 26, 22, 30, 34, 20, 40, 26, 24, 26, 12]
    for j, w in enumerate(larghezze, start=1):
        ws.column_dimensions[openpyxl.utils.get_column_letter(j)].width = w

    out = "repertorio/ARCHIVI_OPERATIVO.xlsx"
    wb.save(out)
    print(f"scritto: {out}")
    print(f"sedi totali: {n_sedi}")
    print(f"domini gia' noti (precompilati): {n_noti}")
    print(f"domini DA CERCARE: {n_sedi - n_noti}")

if __name__ == "__main__":
    main()
